const products = [
  {
    id: 1,
    name: 'Puresun custom Swiss dot kids clothes summer puff sleeves toddler girls dress with carrot embroidery baby girl ruffle dresses',
    images: [
      'https://s.alicdn.com/@sc04/kf/Hb55e50570abb49c2a2627a18cc1cf07fW.jpg',
      'https://s.alicdn.com/@sc04/kf/Hd02b2e0cc56e4594846c0ef24e91ed20D.jpg',
      'https://s.alicdn.com/@sc04/kf/Hedd0e32fdcb4402da31072b1cc555153x.jpg',
      'https://s.alicdn.com/@sc04/kf/H7fb93eea047c4792b74ae372c392aa6f5.jpg',
    ],
    description: `The Puresun Custom Swiss Dot Kids Clothes Summer Puff Sleeves Toddler Girls Dress is a delightful addition to your little one's wardrobe. Made with high-quality Swiss dot fabric, this dress is perfect for warm summer days. It features charming puff sleeves that add a touch of elegance, while the adorable carrot embroidery adds a playful and whimsical element. Your baby girl will look absolutely darling in this ruffle dress, making it ideal for special occasions or everyday wear.`,
    brand: 'Apple',
    category: 'Kids',
    price: 50,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    id: 2,
    name: 'Puresun high quality kids clothes smocked children clothing summer crab embroidery baby girl clothing set with pink gingham',
    images: [
      'https://s.alicdn.com/@sc04/kf/Hef68c7a78e7848a980bc09621bcf5a20a.jpg',
      'https://s.alicdn.com/@sc04/kf/H44d0d17894f740a6923ea813eafef553X.jpg',
      'https://s.alicdn.com/@sc04/kf/H7f3a0d294df1450096bf6f846b1d33e2a.jpg',
      'https://s.alicdn.com/@sc04/kf/H98a5112669204715b08350981883b00aO.jpg',
    ],
    description: `Elevate your little one's wardrobe with the Puresun High-Quality Kids Clothes Smocked Children Clothing Set. Crafted from premium materials, this adorable set is perfect for summer days. The smocked top features charming crab embroidery, adding a playful touch to the ensemble. Paired with pink gingham bottoms, this clothing set strikes the perfect balance between style and comfort. Whether for a day at the beach or a family outing, your baby girl will look irresistibly cute in this outfit.`,
    brand: 'Apple',
    category: 'Kids',
    price: 50,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    id: 3,
    name: '2024 Fashion Girls Clothing Sets Cotton with Custom Applique Big Sister Outfit from Gold Supplier for Kids Clothes',
    images: [
      'https://s.alicdn.com/@sc04/kf/H0c40c9557e044d6fa13113746c658acfm.jpg',
      'https://s.alicdn.com/@sc04/kf/H8c9e2977768341c0a8bcc9d8d1b235d9K.jpg',
      'https://s.alicdn.com/@sc04/kf/Hccfae88356834c6f9c930a40df74a998p.jpg',
      'https://s.alicdn.com/@sc04/kf/Hbe713171ae8e4f32ba9cf58d4ecdb918p.jpg',
    ],
    description: `Introducing the 2024 Fashion Girls Clothing Sets, crafted from premium cotton fabric for ultimate comfort and style. This adorable outfit features a custom applique design, showcasing the message "Big Sister" in a playful and charming manner. Designed with care and attention to detail, this set is perfect for sisters who want to showcase their special bond in style. Whether for casual outings or special occasions, this outfit from our gold supplier is sure to make a statement in the world of kids' fashion.`,
    brand: 'Cannon',
    category: 'Kids',
    price: 60,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    id: 4,
    name: 'Supercute Mochila Escolar Infantil Back To School Mochila Infantil Menina Kids Backpack School Backpack For Children',
    images: [
      'https://s.alicdn.com/@sc04/kf/Hde2a7216c06247d89f2609c660d764baV.jpg',
      'https://s.alicdn.com/@sc04/kf/Hd68033a1cc9f4140888ee97ad397243b7.jpg',
      'https://s.alicdn.com/@sc04/kf/Hfd32cc23ce0649b6aac93c464196b2413.jpg',
      'https://s.alicdn.com/@sc04/kf/H0450b8f3f73c4b78a8af9f11823eac9c4.jpg',
    ],
    description: `Get ready for back-to-school season with our Supercute Mochila Escolar Infantil. This adorable kids backpack is designed with both style and functionality in mind, making it the perfect choice for your little one's school essentials. With its vibrant colors and fun design, it adds a touch of excitement to any school day. The backpack features comfortable straps and ample storage space to carry books, notebooks, stationery, and more. Let your child showcase their unique style with this charming backpack that combines practicality with cuteness.`,
    brand: 'Sony',
    category: 'Kids',
    price: 39,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    id: 5,
    name: "Elegant Women's Summer Dress",
    images: [
      'https://example.com/womens-dress1.jpg',
      'https://example.com/womens-dress2.jpg',
    ],
    description: `This elegant summer dress is perfect for any occasion. Made with lightweight fabric, it features a flattering silhouette and delicate details.`,
    brand: 'Fashionista',
    category: 'Women',
    price: 75,
    countInStock: 20,
    rating: 4.8,
    numReviews: 15,
  },
  {
    id: 6,
    name: "Stylish Men's Casual Shirt",
    images: [
      'https://example.com/mens-shirt1.jpg',
      'https://example.com/mens-shirt2.jpg',
    ],
    description: `This stylish casual shirt is perfect for everyday wear. Made from breathable fabric, it combines comfort with a modern look.`,
    brand: 'Trendsetter',
    category: 'Men',
    price: 45,
    countInStock: 15,
    rating: 4.5,
    numReviews: 10,
  },
  {
    id: 7,
    name: 'Beauty Essentials Makeup Kit',
    images: [
      'https://example.com/makeup-kit1.jpg',
      'https://example.com/makeup-kit2.jpg',
    ],
    description: `This beauty essentials makeup kit includes everything you need for a flawless look. Perfect for both beginners and makeup enthusiasts.`,
    brand: 'Glamour',
    category: 'Beauty',
    price: 50,
    countInStock: 30,
    rating: 4.6,
    numReviews: 20,
  },
  {
    id: 8,
    name: 'Home Decor Decorative Pillow',
    images: [
      'https://example.com/decor-pillow1.jpg',
      'https://example.com/decor-pillow2.jpg',
    ],
    description: `Add a touch of style to your living space with this decorative pillow. Soft and comfortable, it’s perfect for any home decor.`,
    brand: 'HomeStyle',
    category: 'Home',
    price: 25,
    countInStock: 0,
    rating: 4.9,
    numReviews: 30,
  },
]

export default products
